### ISSUE TITLE
huawei-solar

### ISSUE THREAD

**Issue by djsuszi** [szczeles/toolbelt#1]
is it working ?

2020-06-24 22:44:54,949 Login successful, session: xxxx, token: xxxxx
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    last_pushed_ts = pvoutput.get_last_pushed_timestamp()
  File "/api/pvoutput.py", line 51, in get_last_pushed_timestamp
    status = self.get_status()
  File "/api/pvoutput.py", line 48, in get_status
    return Status.parse(data, self.timezone)
  File "/api/pvoutput.py", line 21, in parse
    datetime.strptime(parts[0] + parts[1], '%Y%m%d%H:%M')
IndexError: list index out of range

**Comment by djsuszi** [comment]
from pvoutput I get:

pvoutput = PVOutput(args.pvoutput_system_id, args.pvoutput_api_key, timezone)
pprint(vars(pvoutput))

{'api_key': 'xxxx',
 'system_id': 'xxx',
 'timezone': <DstTzInfo 'Europe/Warsaw' LMT+1:24:00 STD>}

**Comment by szczeles** [comment]
Hi @djsuszi! Yep, it works, at lest for me ;-) https://pvoutput.org/list.jsp?userid=85616

The script expects some initial data being pushed to pvoutput already (to establish stating date of data sync), I will add a new param for fix your case.

**Comment by szczeles** [comment]
@djsuszi Please check if the code from `start_date_param` fixes your issue

**Comment by djsuszi** [comment]
now it works great :)

Have you tried to get more info from Huawei website ?
pvoutput can also get more info like for example voltage or power usage if you've got that data.

**Comment by szczeles** [comment]
That is fantastic news, thanks!

The website allows to get much more data - voltage, current (even separately on pv strings), inverter temperature. The reason I'm not pushing that data now is because I have 3-phase inverter, so couldn't decide what voltage to put.

I've tried to use https://pvmonitor.pl/ for this extended stats, but got some issues with data display (there were zeros).

However, if you'll figure out what params respond to power usage (I don't have a Huawei power meter module), feel free to contribute!
